# .github/workflows/build-and-push.yml

name: Build and Push Custom Runner Image

on:
  # Bu iş akışı, 'main' branch'ine her push yapıldığında çalışsın.
  push:
    branches:
      - main
  # Bu iş akışını manuel olarak da tetikleyebilmek için.
  workflow_dispatch:

jobs:
  build-with-kaniko:
    name: Build Runner with Kaniko
    # Bu işi, GitHub'ın kendi sanal makinelerinde çalıştırıyoruz.
    runs-on: ubuntu-latest

    # ghcr.io'ya yazma izni veriyoruz.
    permissions:
      contents: read
      packages: write

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 3. Build and push with Kaniko
        # Kaniko'yu çalıştıran hazır Action'ı kullanıyoruz.
        uses: aevea/action-kaniko@v0.10.0
        with:
          # Build edilecek imajın tam adı
          image: ghcr.io/my-homelab-platform/homelab-k8s-runner
          # Dockerfile'ın yolu (reponun kök dizininde)
          dockerfile: ./Dockerfile
          # Build context'i (reponun kök dizini)
          context: .
          # Etiket olarak en son commit'in SHA'sını kullanıyoruz
          tags: latest,${{ github.sha }}
