# .github/workflows/build-and-push.yml (Final Versiyon)

name: Build and Push Custom Runner Image on Self-Hosted Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-on-self-hosted:
    name: Build on Self-Hosted Runner
    # İşi, GitHub'ın sanal makinesi yerine KENDİ RUNNER'IMIZA veriyoruz.
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 3. Build and Push with Local Docker
        # Artık Kaniko'ya ihtiyacımız yok. Runner'ımız doğrudan Docker komutlarını çalıştıracak.
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/homelab-k8s-runner:latest .
          docker push ghcr.io/${{ github.repository_owner }}/homelab-k8s-runner:latest
