# .github/workflows/build-and-push.yml (Nihai Versiyon)

name: Build and Push Custom Runner Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-with-kaniko:
    name: Build Custom Runner Image
    # DEĞİŞİKLİK: İşi, GitHub'ın kendi sanal makinelerinde çalıştırıyoruz.
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 3. Build and Push with Kaniko
        uses: aevea/action-kaniko@v0.10.0
        with:
          image: ghcr.io/my-homelab-platform/homelab-k8s-runner
          dockerfile: ./Dockerfile
          context: .
          tags: latest,${{ github.sha }}